### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'type'

### ISSUE THREAD

**Issue by jankoprowski** [flake8-commas/flake8-commas#35]
```
Traceback (most recent call last):
  File "venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/main/application.py", line 322, in run
    self._run(argv)
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/main/application.py", line 306, in _run
    self.run_checks()
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/main/application.py", line 244, in run_checks
    self.file_checker_manager.run()
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/checker.py", line 350, in run
    self.run_serial()
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/checker.py", line 334, in run_serial
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8/checker.py", line 517, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8_commas/_base.py", line 262, in run
    for error in get_comma_errors(tokens):
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8_commas/_base.py", line 198, in get_comma_errors
    for token in tokens:
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8_commas/_base.py", line 122, in simple_tokens
    token = next(tokens)
  File "/home/johny/work/result-api/venv/local/lib/python2.7/site-packages/flake8_commas/_base.py", line 120, in <genexpr>
    tokens = (t for t in tokens if t.type != tokenize.COMMENT)
```

**Comment by CharString** [comment]
I bumped into the same.... Added some version info:

```
$ touch tmp.py
$ flake8 --version
3.2.1 (pyflakes: 1.3.0, flake8_commas._base: 0.4.1, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.13 on Linux
$ flake8 tmp.py 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/CharString/.local/share/virtualenvwrapper/envs/flake8-commas/lib/python2.7/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/home/CharString/.local/share/virtualenvwrapper/envs/flake8-commas/lib/python2.7/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/home/CharString/.local/share/virtualenvwrapper/envs/flake8-commas/lib/python2.7/site-packages/flake8/checker.py", line 517, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/CharString/.local/share/virtualenvwrapper/envs/flake8-commas/lib/python2.7/site-packages/flake8_commas/_base.py", line 262, in run
    for error in get_comma_errors(tokens):
  File "/home/CharString/.local/share/virtualenvwrapper/envs/flake8-commas/lib/python2.7/site-packages/flake8_commas/_base.py", line 198, in get_comma_errors
    for token in tokens:
  File "/home/CharString/.local/share/virtualenvwrapper/envs/flake8-commas/lib/python2.7/site-packages/flake8_commas/_base.py", line 122, in simple_tokens
    token = next(tokens)
  File "/home/CharString/.local/share/virtualenvwrapper/envs/flake8-commas/lib/python2.7/site-packages/flake8_commas/_base.py", line 120, in <genexpr>
    tokens = (t for t in tokens if t.type != tokenize.COMMENT)
AttributeError: 'tuple' object has no attribute 'type'
```

**Comment by janrito** [comment]
https://github.com/flake8-commas/flake8-commas/pull/34 PR fixes this issue

**Comment by iham** [comment]
can someone please merge #34 PR from @janrito and release it on pypi?

this is a real show stopper to me right now and it waits for 21 days now.

thank you!

**Comment by graingert** [comment]
ah woops, I only test this with flake8 on Python 3 :blush:
